sonar.projectKey=xxxxxxxx
sonar.organization=xxxxxxxxxx

sonar.sources=lib,models,routes,app.ts,server.ts
sonar.tests=test
sonar.exclusions=frontend/**,node_modules/**,build/**,dist/**,i18n/**
sonar.test.inclusions=test/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/server-tests/lcov.info,coverage/api-tests/lcov.info
sonar.sourceEncoding=UTF-8
